/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "b4c20624-011f-4f5b-b115-91c1f96db7d2",
    category: "Productivity",
    videoId: "JoL5ukBTwcY",
    creator: "Pick Up Limes",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQFII48R0atMndxGz1n5quE7W1VIpMvJxNnGlUYFg=s68-c-k-c0x00ffffff-no-rj",
    title: "HEALTHY PRODUCTIVITY HABITS » + printable guide",
    description:
      "📚 Get a free 30-day trial for audible at http://audible.com/pickuplimes  \n🤓 Healthy productivity guide (PDF): Visit: http://bit.ly/2gHuvt7-productivity\n🎉 Have you tried a PUL recipe? Leave a review: https://www.pickuplimes.com/recipe/\n👩🏻‍🍳 Get the PUL E-cookbook: http://bit.ly/PUL_Ebook  \n💌  Sign-up for our newsletters: http://bit.ly/PUL_newsletters \n🎥 Film & photography gear we use: https://bit.ly/PUL_filming_gear\n🎶 Music \"Old Man Blanchard\" by Josh Woodward. Free download: http://joshwoodward.com\n\nProductivity is a skill that can be learned. These are some habits I try to practice regularly to stay inspired and productive. Being productive doesn't have to be a chore; it can be enjoyable and rewarding. It's just about planning, focused effort, and above all: putting what we learn to practice ❤\n\nFEATURED IN THE VIDEO\n🫖 Cobblestone ceramic tea set: http://amzn.to/2jeg8Bd\n\nSTAY CONNECTED 🙋🏻‍♀️ \n👉 Instagram: https://www.instagram.com/pickuplimes/ \n👉 TikTok: https://www.tiktok.com/@pick_up_limes \n👉 Facebook: https://www.facebook.com/pickuplimes/ \n👉 Pinterest: https://www.pinterest.com/sadiabadiei/ \n \n❤ Sadia",
    thumbnail: {
      url: "https://i.ytimg.com/vi/JoL5ukBTwcY/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-26T07:45:35Z",
  },
  {
    _id: "6b7bbd84-268f-43cc-883a-3cb85c8d4297",
    category: "Productivity",
    videoId: "ZVneOn6b_Ks",
    creator: "Pick Up Limes",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQFII48R0atMndxGz1n5quE7W1VIpMvJxNnGlUYFg=s68-c-k-c0x00ffffff-no-rj",
    title: "How to stay focused » 7 productivity tips",
    description:
      "👉 Try Notion for free today by using our link: https://ntn.so/pickupnotion\n👩🏻‍💻 Get our free Notion template: https://bit.ly/PUL_Notion_template\n🎉 Have you tried a PUL recipe? Leave a review: https://www.pickuplimes.com/recipe/\n👩🏻‍🍳 Get the PUL E-cookbook: http://bit.ly/PUL_Ebook  \n💌  Sign-up for our newsletters: http://bit.ly/PUL_newsletters \n🎥 Film & photography gear we use: http://pickuplimes.com/gear \n🎶 The music we recommend: http://bit.ly/PUL_Uppbeat​ (free to use in YouTube videos!)\n\nTIMELINE \n00:00 Intro\n00:50 Take control\n01:58 Pick your One Task\n02:56 Perform in your peak \n03:46 Protect your flow\n05:09 Work with the best \n05:27 Our Notion workflow + template \n07:31 Reward yourself  \n08:23 Step back\n08:52 Outro  \n\nWHAT WE USE @ PUL   \n🔪 Knife set: https://amzn.to/2YSH74r\n🎧 Headphones: https://amzn.to/3CanJnv\n📓 Bullet journal: https://amzn.to/361hAL1\n🖊  Pen: https://amzn.to/2EVYUQL\n\nSTAY CONNECTED 🙋🏻‍♀️ \n👉 Instagram: https://www.instagram.com/pickuplimes/ \n👉 TikTok: https://www.tiktok.com/@pick_up_limes \n👉 Facebook: https://www.facebook.com/pickuplimes/ \n👉 Pinterest: https://www.pinterest.com/sadiabadiei/ \n\n❤ Sadia",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ZVneOn6b_Ks/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-26T07:59:20Z",
  },
  {
    _id: "f4872d38-7482-4441-ad22-c40309ba314c",
    category: "Productivity",
    videoId: "cshVfS2LXm0",
    creator: "Robin Sharma",
    creatorImg:
      "https://yt3.ggpht.com/DxgR350GsDpTPiJaBw7VzqOkb0cnVk9NXFj11_0yginziQH8Z9CBY4RiiJ2RH4Zt5iY2-aSXMKQ=s68-c-k-c0x00ffffff-no-rj",
    title: "A Method To x100 Your Productivity | Robin Sharma",
    description:
      "To join Robin Sharma's 30-Day Challenge click here: https://rshar.ma/MonkMethodYT\n\nOrder your copy of Robin Sharma’s new worldwide bestselling book The Everyday Hero Manifesto —  part manual for peerless productivity, part handbook for leading a world-class life and part playbook for spiritual liberty: https://rshar.ma/EHMM\n\nSUBSCRIBE so you don’t miss even one episode of The Daily Mastery Podcast [Robin Sharma’s new podcast]: https://rshar.ma/TheDailyMasteryPodcast\n\nMORE RESOURCES FOR MASTERY:\n\nRobin Sharma’s monthly digital mentoring program The Circle of Legends: https://rshar.ma/YouTubeCOL \n\nFOLLOW ROBIN SHARMA:\n\nInstagram: https://www.instagram.com/robinsharma/\nFacebook: https://www.facebook.com/RobinSharmaOfficial\nTwitter: https://twitter.com/robinsharma\nSoundCloud: https://soundcloud.com/robin_sharma\n\n#robinsharma #leadership #productivity #business #entrepreneur #theeverydayheromanifesto #the5amclub #dailymastery #eliteperformance #themonkwhosoldhisferrari",
    thumbnail: {
      url: "https://i.ytimg.com/vi/cshVfS2LXm0/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T13:06:46Z",
  },
  {
    _id: "ff52226c-de04-4b15-aec2-8dadb17e4912",
    category: "Productivity",
    videoId: "U0gvKt7TKic",
    creator: "warikoo",
    creatorImg:
      "https://yt3.ggpht.com/X9eoDIB9cgb1s-kvATRs1lQDcU4Fjc15NDV9s9FF8ck7IsA8u7OdijaernoDV9LLdePgjlt_=s88-c-k-c0x00ffffff-no-rj",
    title:
      "10 Productivity tips and tricks that work | Ankur Warikoo Hindi Video | How to be more productive",
    description:
      "In this video I will share with you 10 #productivity hacks that I use on a daily basis to maximize my outcome.\n\nI am a productivity nerd and love to think about things that maximize how much I can get done, within a limited amount of time. So a lot of what I do in life is highly organised and #process driven. \n\nIn this video, I share some tips that have helped me stay as productive as possible, and I hope at least some of them can help you too! Feel free to leave your own productivity tips in the comments to help others, and let me know if you have any questions :)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/U0gvKt7TKic/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T13:36:06Z",
  },
  {
    _id: "b5a10b3d-9aa0-427d-830b-5532eab99d9c",
    category: "Productivity",
    videoId: "FBHNInnA3Pg",
    creator: "Malama Life",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRFBfek7NIiLCScaCv9x7QzfHeLQq3s3IirsfeI=s68-c-k-c0x00ffffff-no-rj",
    title:
      "6 Powerful Journaling Techniques | For Clarity, Creativity, Productivity",
    description:
      "Hi everyone! In today's video, I'll be sharing with you 6 Powerful Journaling Techniques for Mental Clarity.  I hope this is helpful \n\nThe Original Bullet Journal: https://www.youtube.com/watch?v=fm15cmYU0IM\n\n\n-C O M E  S A Y  H I-\nInstagram: https://www.instagram.com/malamalife/\nWebsite: www.malama-life.com\n\n-I N Q U I R I E S-\nsophie.malamalife@gmail.com\n\n-M U S I C-\nhttps://www.epidemicsound.com/referral/iw5a6z/\n\n-C A M E R A  G E A R-\nMain Camera: https://amzn.to/30fW97P\nSecond Camera: https://amzn.to/2HuU8y7\nFilming Lens: https://amzn.to/2S6V6CT\nSD card: https://amzn.to/3cCWeHT\n\nDISCLAIMER: Links included in this description may be affiliate links. If you purchase a product with the links that I provide, I may receive a small commission. However, there is no additional charge to you. I appreciate your support.\n\nThanks for joining this community!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/FBHNInnA3Pg/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T14:02:36Z",
  },
  {
    _id: "b9dc5cf5-b91a-4d0a-a446-1bf0d4f60022",
    category: "Productivity",
    videoId: "E6fmiWkMJ_w",
    creator: "Sheldon Evans",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQs6kaWeC1Vi9Rr9PJ1zzHxPoDK4dka5jGnc7-mFQ=s68-c-k-c0x00ffffff-no-rj",
    title: "Journaling for Productivity | My MINIMALIST BULLET JOURNAL",
    description:
      "Join the intentional living email list » https://bit.ly/SE-Living\n\n» The Journal I use: https://amzn.to/37F1iqX\n» Film & photography gear I use: http://kit.co/SheldonEvans\n» Music: http://bit.ly/38GC3WH (great for YouTubers)\n\n------------\n\nReach me!\n» Twitter: https://twitter.com/SheldonEvans\n» Instagram: https://www.instagram.com/sheldonevansx\n\nHere's a little how to guide for you to follow along if you want to implement the super simple bullet journalling technique that I use to organise and plan my life.\n\n#bulletjournal #productivity #minimalism",
    thumbnail: {
      url: "https://i.ytimg.com/vi/E6fmiWkMJ_w/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T18:40:36Z",
  },
  {
    _id: "c541d4f1-e716-4c97-b0fe-a86e92b0664f",
    category: "Productivity",
    videoId: "fm15cmYU0IM",
    creator: "Bullet Journal",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSfvSdxMhNsciAwH-0ouwbmRu4Gfi6e5-dLE3up=s68-c-k-c0x00ffffff-no-rj",
    title: "How to Bullet Journal",
    description:
      "Hi, let me give you a brief overview of a method I invented that will help you track the past, organize the present, and plan for the future. I call it the Bullet Journal®, it's an analog system for the digital age. All you need to get started is a notebook and a pen. I hope it serves you well. \n\nBest, \nRyder (Creator of the Bullet Journal®)\n\n__________________\n\nRESOURCES\n\n‣ More on the Bullet Journal method: http://Bulletjournal.com\n\n___________________\n\nFOLLOW\n\n‣ Business Inquiries: support@bulletjournal.com\n‣ Newsletter: https://promotions.lpage.co/campaigns/384701\n‣ Instagram: http://instagram.com/bulletjournal\n‣ Facebook: https://www.facebook.com/bulletjournal\n‣ Twitter: https://www.twitter.com/rydercarroll\n\n___________________\n\nGEAR\n\n‣ Book: https://bulletjournal.com/pages/book\n‣ Notebook: https://bulletjournal.com/products/notebook",
    thumbnail: {
      url: "https://i.ytimg.com/vi/fm15cmYU0IM/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T18:40:44Z",
  },
  {
    _id: "c4749a72-1d89-4b37-b409-d65d7b30ff38",
    category: "Productivity",
    videoId: "ZK5VUuxGYr0",
    creator: "Pick Up Limes",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQFII48R0atMndxGz1n5quE7W1VIpMvJxNnGlUYFg=s68-c-k-c0x00ffffff-no-rj",
    title: "Minimal bullet journal setup » for productivity + mindfulness",
    description:
      "📚 Visit http://www.audible.com/pickuplimes to get 1 free audiobook + 2 Audible originals + a 30 day free trial \n🎉 Have you tried a PUL recipe? Leave a review: https://www.pickuplimes.com/recipe/\n👩🏻‍🍳 Get the PUL E-cookbook: http://bit.ly/PUL_Ebook  \n💌  Sign-up for our newsletters: http://bit.ly/PUL_newsletters \n🎥 Film & photography gear we use: https://bit.ly/PUL_filming_gear\n🎶 The music we recommend: http://bit.ly/PUL_Uppbeat​ (free to use in YouTube videos!)\n\nFEATURED \n📓 Bullet journal: https://amzn.to/361hAL1\n🖊 Pen: https://amzn.to/2EVYUQL\n🌈 Markers: https://amzn.to/3659d0I\n📌 Washi tape: https://amzn.to/2ETvBhQ\n\nWHAT WE USE @ THE PUL KITCHEN (2019) \n» Blender: https://amzn.to/2GfbeL6 \n» Food processor: https://amzn.to/2IquU2b \n» Hand blender: https://amzn.to/2PojlJM \n» Cast iron pot: https://amzn.to/2WtKDT6 \n» Mini spice jars: http://amzn.to/2exHWP8 \n» Air-tight containers: http://amzn.to/2iPXmiW \n» Mason jars: https://amzn.to/2tekWbH \n» Garlic crusher: https://amzn.to/2G8d4zY \n» Bento boxes:  http://amzn.to/2x0si6E \n» Measuring cups: https://amzn.to/2TfNxt9 \n» Measuring spoons: https://amzn.to/2KIkfj4 \n» For delicious recipes, visit: http://www.pickuplimes.com \n\nSTAY CONNECTED 🙋🏻‍♀️ \n👉 Instagram: https://www.instagram.com/pickuplimes/ \n👉 TikTok: https://www.tiktok.com/@pick_up_limes \n👉 Facebook: https://www.facebook.com/pickuplimes/ \n👉 Pinterest: https://www.pinterest.com/sadiabadiei/ \n\n❤ Sadia",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ZK5VUuxGYr0/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T18:40:55Z",
  },

  {
    _id: "c6b6986c-5c82-49e9-9c33-004fd33aff04",
    category: "Wellness",
    videoId: "x3nIBdywwnY",
    creator: "Pick Up Limes",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQFII48R0atMndxGz1n5quE7W1VIpMvJxNnGlUYFg=s68-c-k-c0x00ffffff-no-rj",
    title: "mindsets for GROWTH and POSITIVE thinking",
    description:
      '📚 Visit http://www.audible.com/pickuplimes to get 1 free audiobook + 2 free Audible originals + a 30 day free trial \n🎉 Have you tried a PUL recipe? Leave a review: https://www.pickuplimes.com/recipe/\n👩🏻‍🍳 Get the PUL E-cookbook: http://bit.ly/PUL_Ebook  \n💌  Sign-up for our newsletters: http://bit.ly/PUL_newsletters \n🎥 Film & photography gear we use: https://bit.ly/PUL_filming_gear\n🎶 The music we use: http://bit.ly/YTube_music (great for YouTube creators) \n\nTIMELINE\n00:00 Intro\n00:25 Mindset #1: Focus on possibilities in place of limitations \n01:42 Mindset #2: Always ask "why"\n02:54 Mindset #3: Prioritizing creativity & play\n04:25 Mindset #4: Small steps lead to big changes \n05:55 Mindset #5: Taking care of me for you\n07:11 Audible \n\nRESOURCES\n🤓 FREE habit tracker PDF: https://bit.ly/mindset_PDF\n🤓  PUL\'s favourite audiobooks: https://bit.ly/PUL_fave_books\n\nWHAT WE USE @ THE PUL KITCHEN (2019)\n» Blender: https://amzn.to/2GfbeL6\n» Food processor: https://amzn.to/2IquU2b\n» Hand blender: https://amzn.to/2PojlJM\n» Cast iron pot: https://amzn.to/2WtKDT6\n» Mini spice jars: http://amzn.to/2exHWP8\n» Air-tight containers: http://amzn.to/2iPXmiW\n» Mason jars: https://amzn.to/2tekWbH\n\nSTAY CONNECTED 🙋🏻‍♀️ \n👉 Instagram: https://www.instagram.com/pickuplimes/ \n👉 TikTok: https://www.tiktok.com/@pick_up_limes \n👉 Facebook: https://www.facebook.com/pickuplimes/ \n👉 Pinterest: https://www.pinterest.com/sadiabadiei/ \n \n❤ Sadia',
    thumbnail: {
      url: "https://i.ytimg.com/vi/x3nIBdywwnY/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-25T21:05:00Z",
  },
  {
    _id: "1e445e6c-b2c9-4493-a11b-68531e0c6fdd",
    category: "Wellness",
    videoId: "4dzsrT_pzC0",
    creator: "Pick Up Limes",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQFII48R0atMndxGz1n5quE7W1VIpMvJxNnGlUYFg=s68-c-k-c0x00ffffff-no-rj",
    title: "DECREASING STRESS » finding calm + patience",
    description:
      "🎉 Have you tried a PUL recipe? Leave a review: https://www.pickuplimes.com/recipe/\n👩🏻‍🍳 Get the PUL E-cookbook: http://bit.ly/PUL_Ebook  \n💌  Sign-up for our newsletters: http://bit.ly/PUL_newsletters \n🎥 Film & photography gear we use: https://bit.ly/PUL_filming_gear\n🎶 The music we use: http://bit.ly/YTube_music (great for YouTube creators) \n🫖 Cobblestone ceramic tea set: http://amzn.to/2jeg8Bd\n📌 The giveaway is now closed, thanks to all who had entered! \n\nThere is nothing unnatural or bad about stress, what's most important is how we deal with that stress. We're all unique when it comes to which stress management techniques work best, so I welcome you to try some new methods that you haven't already. Chin up, beautiful - you've got this ❤\n\nWHAT WE USE @ THE PUL KITCHEN (2019)\n» Blender: https://amzn.to/2GfbeL6\n» Food processor: https://amzn.to/2IquU2b\n» Hand blender: https://amzn.to/2PojlJM\n» Cast iron pot: https://amzn.to/2WtKDT6\n» Mini spice jars: http://amzn.to/2exHWP8\n» Air-tight containers: http://amzn.to/2iPXmiW\n» Mason jars: https://amzn.to/2tekWbH\n\nSTAY CONNECTED 🙋🏻‍♀️ \n👉 Instagram: https://www.instagram.com/pickuplimes/ \n👉 TikTok: https://www.tiktok.com/@pick_up_limes \n👉 Facebook: https://www.facebook.com/pickuplimes/ \n👉 Pinterest: https://www.pinterest.com/sadiabadiei/ \n \n❤ Sadia",
    thumbnail: {
      url: "https://i.ytimg.com/vi/4dzsrT_pzC0/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-25T21:16:07Z",
  },
  {
    _id: "768eeb99-809d-4179-b64b-9a6ef201849d",
    category: "Wellness",
    videoId: "qziBpNkox3w",
    creator: "Pick Up Limes",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQFII48R0atMndxGz1n5quE7W1VIpMvJxNnGlUYFg=s68-c-k-c0x00ffffff-no-rj",
    title: "Overcoming feelings of failure",
    description:
      "📚  Visit http://www.audible.com/pickuplimes to get 1 free audiobook + 2 free Audible originals + a 30 day free trial \n🎉 Have you tried a PUL recipe? Leave a review: https://www.pickuplimes.com/recipe/\n👩🏻‍🍳 Get the PUL E-cookbook: http://bit.ly/PUL_Ebook  \n💌  Sign-up for our newsletters: http://bit.ly/PUL_newsletters \n🎥 Film & photography gear we use: https://bit.ly/PUL_filming_gear\n🎶 The music we use: http://bit.ly/YTube_music (great for YouTube creators) \n\nWHAT WE USE @ THE PUL KITCHEN (2019) \n» Blender: https://amzn.to/2GfbeL6 \n» Food processor: https://amzn.to/2IquU2b \n» Hand blender: https://amzn.to/2PojlJM \n» Cast iron pot: https://amzn.to/2WtKDT6 \n» Mini spice jars: http://amzn.to/2exHWP8 \n» Air-tight containers: http://amzn.to/2iPXmiW \n» Mason jars: https://amzn.to/2tekWbH \n» Garlic crusher: https://amzn.to/2G8d4zY \n» Bento boxes:  http://amzn.to/2x0si6E\n» Measuring cups: https://amzn.to/2TfNxt9\n» Measuring spoons: https://amzn.to/2KIkfj4\n\nSTAY CONNECTED 🙋🏻‍♀️ \n👉  Instagram: https://www.instagram.com/pickuplimes/ \n👉 TikTok: https://www.tiktok.com/@pick_up_limes \n👉 Facebook: https://www.facebook.com/pickuplimes/ \n👉 Pinterest: https://www.pinterest.com/sadiabadiei/ \n\n❤ Sadia",
    thumbnail: {
      url: "https://i.ytimg.com/vi/qziBpNkox3w/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-25T21:23:09Z",
  },
  {
    _id: "deb22f73-d613-4b74-8b7f-8d01c79cd147",
    category: "Wellness",
    videoId: "RYuMxWP-Wf0",
    creator: "Pick Up Limes",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQFII48R0atMndxGz1n5quE7W1VIpMvJxNnGlUYFg=s68-c-k-c0x00ffffff-no-rj",
    title: "How to deal with overthinking & worrying 😌",
    description:
      "🎉 Have you tried a PUL recipe? Leave a review: https://www.pickuplimes.com/recipe/\n👩🏻‍🍳 Get the PUL E-cookbook: http://bit.ly/PUL_Ebook  \n💌  Sign-up for our newsletters: http://bit.ly/PUL_newsletters \n🎥 Film & photography gear we use: https://bit.ly/PUL_filming_gear\n🎶 The music we recommend: http://bit.ly/PUL_Uppbeat​ (free to use in YouTube videos!)\n\nTIMELINE & RECIPES \n00:00 Intro \n01:06 Why we overthink & worry\n03:29 Things we have no control over \n04:54 Things we have control over\n06:07 Summary\n06:44 Outro \n \nMORE VIDEOS YOU MIGHT ENJOY \n🌱 A habit worth breaking: https://youtu.be/WYgsX-FonfY\n🌱 Living lightly: https://youtu.be/ziUq2NJI-Ps\n🌱 Building good habits effectively: https://youtu.be/pc3M3cH6iJo\n\nWHAT WE USE @ THE PUL KITCHEN   \n» Cast iron pot: https://amzn.to/2WtKDT6   \n» Immersion blender: https://amzn.to/2ZtFo9T \n» Cutting board: https://amzn.to/36oiJgC \n» Garlic crusher: https://amzn.to/2G8d4zY  \n» Mini spice jars: https://amzn.to/2xXSP69 \n» Air-tight containers: http://amzn.to/2iPXmiW  \n» Large glass storage jars: https://amzn.to/2TnLqUk\n» Mason jars: https://amzn.to/2tekWbH  \n» Measuring cups/spoons: https://amzn.to/3vAqpY1\n\nSTAY CONNECTED 🙋🏻‍♀️ \n👉 Instagram: https://www.instagram.com/pickuplimes/ \n👉 TikTok: https://www.tiktok.com/@pick_up_limes \n👉 Facebook: https://www.facebook.com/pickuplimes/ \n👉 Pinterest: https://www.pinterest.com/sadiabadiei/ \n\n❤ Sadia",
    thumbnail: {
      url: "https://i.ytimg.com/vi/RYuMxWP-Wf0/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-26T07:36:32Z",
  },
  {
    _id: "c57fe433-7b2f-452a-9545-f4e065805d67",
    category: "Wellness",
    videoId: "9ED8i-xX5g0",
    creator: "Malama Life",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRFBfek7NIiLCScaCv9x7QzfHeLQq3s3IirsfeI=s68-c-k-c0x00ffffff-no-rj",
    title: "Real Self-Love Habits That Changed Me 💗",
    description:
      "“Vulnerability is not winning or losing; it’s having the courage to show up and be seen when we have no control over the outcome. Vulnerability is not weakness; it’s our greatest measure of courage.” Brené Brown, Rising Strong\n\nRising Strong: https://amzn.to/3GUitX4\n\n#selflove #selflovehabits\n\n-C O M E  S A Y  H I-\nMy Personal Channel: https://www.youtube.com/sophiedaquis\nInstagram: https://www.instagram.com/malamalife/\nWebsite: www.malama-life.com\nPoshmark: www.poshmark.com/closet/malamalife\nSpotify: https://open.spotify.com/show/1P4wRl1iESmfh3Z9Z08GZi?si=yeN0xPbrRFaGAfn54REuqg\n\n-I N Q U I R I E S-\nsophie.malamalife@gmail.com\n\n-M U S I C-\nhttps://www.epidemicsound.com/referral/iw5a6z/\n\n-C A M E R A  G E A R-\n(All videos are filmed and edited by me)\nMain Camera: https://amzn.to/30fW97P\nSecond Camera: https://amzn.to/2HuU8y7\nMain Filming Lens: https://amzn.to/3epfJ9U\nMicrophone: https://amzn.to/3epBgzc\nTripod: https://amzn.to/3vkU3RQ\nSD card: https://amzn.to/3cCWeHT\nData Storage: https://amzn.to/3rLvzjK\n\n\nDISCLAIMER: Links included in this description may be affiliate links. If you purchase a product with the links that I provide, I may receive a small commission. However, there is no additional charge to you. I appreciate your support!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/9ED8i-xX5g0/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-26T21:48:10Z",
  },
  {
    _id: "24c21c5f-0ffa-4b4e-b877-792c18bacfba",
    category: "Wellness",
    videoId: "xAxOMJYwN4I",
    creator: "Malama Life",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRFBfek7NIiLCScaCv9x7QzfHeLQq3s3IirsfeI=s68-c-k-c0x00ffffff-no-rj",
    title: "10 Relaxing Things To Do By Yourself | Self Care Habits",
    description:
      "As an introvert, I value my alone time more than anything. These are some of the activities that I enjoy the most to recharge and regain my peace of mind. I hope you enjoy :)\n\nThank you so much for watching and always appreciate your support.\n\n\n-COME SAY HI-\nInstagram: https://www.instagram.com/malamalife/\n\n-INQUIRIES-\nsophie.malamalife@gmail.com\n\n-CAMERA GEAR-\nMain Camera: https://amzn.to/30fW97P\nSecond Camera: https://amzn.to/2HuU8y7\nFilming Lens: https://amzn.to/2S6V6CT\nSD card: https://amzn.to/3cCWeHT\n\nDISCLAIMER: Links included in this description may be affiliate links. If you purchase a product with the links that I provide, I may receive a small commission. However, there is no additional charge to you. I appreciate your support.\n\nThank you for subscribing!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/xAxOMJYwN4I/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T13:54:47Z",
  },
  {
    _id: "21f24cc0-a66a-4ca9-ac27-dffb2448902a",
    category: "Wellness",
    videoId: "MaUOvqND63A",
    creator: "Ashlynne Eaton",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQn3Qil0D0aDGf8LG9gNdmKj7bXOef_O4TiLwuk0g=s68-c-k-c0x00ffffff-no-rj",
    title:
      "7 TINY Ways To Take Better CARE Of Yourself in 2021 | Self Care Habits",
    description:
      "► CARE/OF: Click here https://bit.ly/37lCU0F and use my code ASHLYNNE50 for 50% off your first month at Care/of! 🎉\n\nCare/of works hard to recommend supplements based on scientific research and your personal goals. As a friendly reminder, supplements aren’t intended to diagnose, treat, cure, or prevent any disease.\n \nToday, I’m sharing 7 small ways to take better care of yourself + live a more intentional life in 2021! ✨\n\n► JOIN THE PARTY ON INSTAGRAM\n    » Instagram: https://www.instagram.com/ashlynne.eaton/\n\n► WHAT I’M WEARING\n    » Cardigan: https://bit.ly/rebelocardigan \n    » Necklace: http://www.analuisa.com/Ashlynne/ \n        (I’m wearing the Ming Ming necklace)\n\nNew here? Welcome to my channel! I post videos every week about simple and intentional living. If you’re looking to embrace simplicity or just appreciate how life can be better with less, be sure to subscribe! \n\n► GET CONNECTED\n    » Website: https://ashlynneeaton.com/\n    » Instagram: https://www.instagram.com/ashlynne.eaton/ \n    » Facebook: https://www.facebook.com/ashlynneeaton/ \n    » Pinterest: https://www.pinterest.com/ashlynneeaton/ \n\n► MY FAVORITE MINIMALISM & INTENTIONAL LIVING BRANDS\n    » Everlane: https://www.everlane.com/r/ashlynneeaton  \n    » Organic Basics: http://organicbasics.pxf.io/ashlynne \n        (Use code “ASHLOBC” for 10% off)\n    » Nisolo:  http://bit.ly/31rQIRR\n    » Ana Luisa: http://www.analuisa.com/Ashlynne/ \n\n► FTC \n    » This video is kindly sponsored by Care/of. All opinions shared are my own. Some of the links above are affiliate links and when you use them, they help to support me and my channel! 🤍",
    thumbnail: {
      url: "https://i.ytimg.com/vi/MaUOvqND63A/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T13:55:30Z",
  },
  {
    _id: "ca62c14f-e293-4d7b-ad74-a05ce44ee239",
    category: "Wellness",
    videoId: "inpok4MKVLM",
    creator: "Goodful",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQ-dffKGPYK6pcttjIHITxxC5iHeAoF1ioZ9fNx=s68-c-k-c0x00ffffff-no-rj",
    title: "5-Minute Meditation You Can Do Anywhere",
    description:
      "In just 5 minutes you can reset your day in a positive way.\n\nSpecial thanks to John Davisi for lending us his incredibly soothing voice. https://www.johndavisi.com/\nhttps://www.youtube.com/c/JohnDavisi",
    thumbnail: {
      url: "https://i.ytimg.com/vi/inpok4MKVLM/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T18:25:16Z",
  },
  {
    _id: "1dfdb5cf-20f8-4787-8a7d-b1ab8873b1f0",
    category: "Wellness",
    videoId: "O-6f5wQXSu8",
    creator: "Goodful",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQ-dffKGPYK6pcttjIHITxxC5iHeAoF1ioZ9fNx=s68-c-k-c0x00ffffff-no-rj",
    title: "10-Minute Meditation For Anxiety",
    description:
      "Take a moment and let this guided meditation relieve your anxiety.\n\nWritten and Narrated by John Davisi. John is a mindfulness life coach, teacher, and speaker. Check out his mindfulness and meditation sessions at https://www.youtube.com/c/JohnDavisi .\n\nSubscribe to John Davisi: https://www.youtube.com/c/JohnDavisi\n\nSubscribe to Goodful: https://bzfd.it/2QApoPk\n\nAbout Goodful:\nFeel better, be better, and do better. Subscribe to Goodful for all your healthy self care needs, from food to fitness and everything in between!\n\nConnect with Goodful:\nLike us on Facebook: https://www.facebook.com/officialgoodful/\nFollow us on Instagram: https://www.instagram.com/goodful/\nFollow us on Twitter: https://twitter.com/goodful\nCheck out our website: https://www.goodful.com/\nSubscribe to the Goodful Newsletter: https://www.buzzfeed.com/newsletters/goodful\n\nCredits: https://www.buzzfeed.com/bfmp/videos/102576\nMUSIC\n\nLicensed via Audio Network\n\n\n\n\nhttps://www.youtube.com/c/Goodful",
    thumbnail: {
      url: "https://i.ytimg.com/vi/O-6f5wQXSu8/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T18:29:56Z",
  },
  {
    _id: "f59137b9-2b11-43c8-8eb0-9bae8e6c6abe",
    category: "Wellness",
    videoId: "z6X5oEIg6Ak",
    creator: "Goodful",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQ-dffKGPYK6pcttjIHITxxC5iHeAoF1ioZ9fNx=s68-c-k-c0x00ffffff-no-rj",
    title: "10-Minute Meditation For Stress",
    description:
      "If you are feeling stressed or overwhelmed, listen to this guided meditation to re-center yourself.\n\nWritten and Narrated by John Davisi. John is a mindfulness life coach and speaker. Check out his other mindfulness and meditation sessions at https://www.youtube.com/c/johndavisi\n\nSubscribe to Goodful: https://bzfd.it/2QApoPk\n\nGoodful\nFeel better, be better, and do better. Subscribe to Goodful for all your healthy self care needs, from food to fitness and everything in between!\n\nConnect with Goodful:\nLike us on Facebook: https://www.facebook.com/officialgood...\nFollow us on Instagram: https://www.instagram.com/goodful/\nFollow us on Twitter: https://twitter.com/goodful\nCheck out our website: https://www.goodful.com/\nSubscribe to the Goodful Newsletter: https://www.buzzfeed.com/newsletters/goodful\n\nGET MORE BUZZFEED:\nhttps://www.buzzfeed.com\nhttps://www.buzzfeed.com/videos\nhttps://www.youtube.com/buzzfeedvideo\nhttps://www.youtube.com/asis\nhttps://www.youtube.com/buzzfeedmultiplayer\nhttps://www.youtube.com/buzzfeedunsolvednetwork\nhttp://youtube.com/buzzfeedceleb\nhttps://www.youtube.com/perolike\nhttps://www.youtube.com/buzzfeedviolet\nhttps://www.youtube.com/goodful\nhttps://www.youtube.com/nifty\nhttps://www.youtube.com/buzzfeedtasty\nhttps://www.youtube.com/bringme\n\nSUBSCRIBE TO BUZZFEED NEWSLETTERS:\nhttps://www.buzzfeed.com/newsletters\n\nCredits: https://www.buzzfeed.com/bfmp/videos/110235\nMUSIC\n\nLicensed via Audio Network\n\n\n\nEXTERNAL CREDITS\nJohn Davisi\nhttps://www.instagram.com/johndavisi/?hl=en\nhttps://www.youtube.com/c/Goodful",
    thumbnail: {
      url: "https://i.ytimg.com/vi/z6X5oEIg6Ak/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-27T18:30:02Z",
  },
  {
    _id: "e684dc25-9ad7-4f59-ad86-4fd42de30949",
    category: "Music",
    videoId: "62d2QvWAVt4",
    creator: "Little Soul",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLR0H2JKhE8PtcaJUHCwf25YswYG7lvsyqlI_tbv=s68-c-k-c0x00ffffff-no-rj",
    title:
      "Music to put you in a better mood ~ A playlist lofi for study, relax, stress relief",
    description:
      '🎶 Listen to "Little Soul" on Spotify : https://open.spotify.com/playlist/6YuSe3suuEWlaizQKtyVkX\n🍀 Art by 3am.in.jupiter\nhttps://www.instagram.com/3am.in.jupiter/\nhttps://linktr.ee/3aminjupiter\n\nAll pictures are collected by me or sent by fans, I just create more. ',
    thumbnail: {
      url: "https://i.ytimg.com/vi/62d2QvWAVt4/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T15:54:23Z",
  },
  {
    _id: "5a4351e4-edd3-4862-ae8a-f080b7e2aa0a",
    category: "Music",
    videoId: "9CL34BQxmEs",
    creator: "The Sherry Formula",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTKL0TbtOyN48Ye8TtEGkpe_24JwK_ly9gcDuHc=s68-c-k-c0x00ffffff-no-rj",
    title:
      "🌿 3-HOUR STUDY MUSIC PLAYLIST/ relaxing Lofi / Cozy Evening DEEP FOCUS POMODORO TIMER/ Study With Me",
    description:
      "Thanks for tuning in :) \nHope this COZY TREEHOUSE AFTERNOON STUDY SESSION 🌿 makes your studying/working more enjoyable. \n\nIf you like this video, don't forget to thumbs up 👍 and subscribe 🔔\n\nTo ease you into today's productive sessions, \nthis Study With Me has five 30-min sessions with 5-min breaks in between:\n→ 🏁 Intro: 00:00:00\n→ 🌿 Session #1: 00:01:22\n→ ☕ Break: 00:31:26\n→ 🌿 Session #2: 00:36:28\n→ ☕ Break: 01:07:02\n→ 🌿 Session #3: 01:12:05\n→ ☕ Break: 01:42:23\n→ 🌿 Session #4: 01:47:25\n→ ☕ Break: 02:17:59\n→ 🌿 Session #5: 02:23:01\n→ ⏹️ Outro: 02:53:18\n\nHope you guys enjoy it :)\n\n------------------------------------------\n\n❐ JOIN THE SHERRY FORMULA COMMUNITY✨ https://bit.ly/350ymdi ❏ \n\n❐ SOCIALS ❏ \n✧ Website: https://www.thesherryformula.com\n✧ Instagram: https://www.instagram.com/thesherryformula/\n✧ Facebook: https://www.facebook.com/thesherryformula/\n✧ Spotify: https://spoti.fi/3DvKHGl\n\n------------------------------------------\n\n❐ More to Watch ❏ \n➦More Study With Me Sessions: https://bit.ly/3tMkwaJ\n\n------------------------------------------\n\n❐ VIDEOGRAPHY ❏ \n\nRoyalty-Free Music (Amazing for YouTubers: sign up for two free months): \n→Artlist: https://bit.ly/3IUh9oa\n→Epidemic Sound: https://www.epidemicsound.com/referral/h2q334\n\nRoyalty-Free Stock Footage (Sign Up for 2 Months Free)   \n→Artgrid: https://bit.ly/381n3ai\n\nSpecial Video Editing Effects (such as countdown timer)\n→Motion Array: https://bit.ly/36x4xXf\n\nYoutube SEO Optimizer: \n→https://www.tubebuddy.com/thesherryformula\n\n------------------------------------------\n\n🎧 | Support the Artists:\n→Nom Tunes: https://bit.ly/3kPVy7j\n→Jordy Chandra: https://bit.ly/3oNJBB0\n→S N U G (Ryan Chen): https://bit.ly/3t7mhkT\n→Dreamhp Music: https://spoti.fi/3fNpOgA\n\n------------------------------------------\n❐ FOR BUSINESS INQUIRIES ❏ \nthesherryformula@gmail.com",
    thumbnail: {
      url: "https://i.ytimg.com/vi/9CL34BQxmEs/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T15:58:53Z",
  },
  {
    _id: "fda1f740-571a-4721-b24c-bfc7d55b0e4d",
    category: "Music",
    videoId: "JLJqUipWRWk",
    creator: "Meditation and Healing",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSluEnX4IkbRTSrdmYN61t_A6Mja2Yvav75YGDtKQ=s68-c-k-c0x00ffffff-no-rj",
    title:
      '"Instant Relief From Anxiety & Stress" Peaceful Meditation Music, Deep Relaxing & Healing Music',
    description:
      '"Instant Relief From Anxiety & Stress" Peaceful Meditation Music, Deep Relaxing & Healing Music by Meditation and Healing.\nThis is 1 hour peaceful piano relaxing and meditation music which helps you to relief from all the stress and anxiety. This instrumental background music helps you for better sleep, relax your mind body and helps you for better sleep. ',
    thumbnail: {
      url: "https://i.ytimg.com/vi/JLJqUipWRWk/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T16:04:53Z",
  },
  {
    _id: "b747935c-2125-4657-9e02-86fb0f96ba0f",
    category: "Music",
    videoId: "PszSx4HvKAA",
    creator: "Yellow Brick Cinema - Relaxing Music",
    creatorImg:
      "https://yt3.ggpht.com/ES-t-ybBvgAdle8NuwJxroid-XE8z02KACkeVPL_5vE3ApE5nYBUTKT98ZMyr0e3RBJumIsk-w=s68-c-k-c0x00ffffff-no-rj",
    title:
      "Tibetan Music, Healing Music, Relaxation Music, Chakra, Relaxing Music for Stress Relief, ✿3193C",
    description:
      "Get the new Yellow Brick Cinema iOS app for a 7-day FREE trial: https://apple.co/30uHqHe\n\nTibetan Music, Healing Music, Relaxation Music, Chakra, Relaxing Music for Stress Relief, ✿3193C - Does the sound of healing Tibetan music and Tibetan Flute music for chakra re-alignment appeal to you? Yellow Brick Cinema’s Tibetan music, Shamanic music and flute music, enhanced with flute, is Zen music that provides soothing music for meditation and chakra meditation. ",
    thumbnail: {
      url: "https://i.ytimg.com/vi/PszSx4HvKAA/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T16:07:50Z",
  },
  {
    _id: "d93fa53f-6e61-4dfe-860a-03bedc26ca12",
    category: "Music",
    videoId: "6kticX9eW_A",
    creator: "The Sould of Wind",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTivkf5vB91lhwxCFmsmiDbHHBzxfh5aAig3iC1AQ=s68-c-k-c0x00ffffff-no-rj",
    title:
      "Relaxing Sleep Music + Stress Relief - Relaxing Music, Deep Sleep Instantly, Night Coffee Music",
    description:
      "Relaxing Sleep Music + Stress Relief - Relaxing Music, Deep Sleep Instantly, Night Coffee Music\n\nArtist: BigRicePiano\nTrack: Polaris\n\n~ BigRicePiano ~\n- https://spoti.fi/3ysT8zT\n- https://apple.co/3ww1HZu\n- https://bigrice.bandcamp.com\n- https://www.youtube.com/c/BigRicePiano\n\n~ Wallpaper: pasopuchi ~\n- https://twitter.com/pasopuchi\n- https://www.instagram.com/pasoputi_\n- https://www.pixiv.net/users/12064216\n- https://pasoputi.fanbox.cc/\n\n~ The Soul of Wind ~\n- Fanpage: https://goo.gl/hJJHc9\n- Twitter: https://goo.gl/iQf1cK\n\nThank you very much for listening. Enjoy relaxing, Sleeping, Meditation Music and have a wonderful day or evening!\n\n#SleepInstantly #PianoMusic #CoffeeMusic\n\n\n_The Soul of Wind_",
    thumbnail: {
      url: "https://i.ytimg.com/vi/6kticX9eW_A/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T16:08:49Z",
  },
  {
    _id: "6d13ca5c-74fe-49ff-9989-b21b21dbc317",
    category: "Music",
    videoId: "vfdwtIOD1Vw",
    creator: "HALIDONMUSIC",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTu-zotMSbbW1MbyBpwsYAAqRyLfjuwYVZCwWg4dQ=s68-c-k-c0x00ffffff-no-rj",
    title: "Classical Music for Working",
    description:
      "🎵 Buy the MP3 album on the Halidon Music Store: https://bit.ly/38iRfdd\n🎧 Listen to our playlist on Spotify: https://bit.ly/MusicForWorking ",
    thumbnail: {
      url: "https://i.ytimg.com/vi/vfdwtIOD1Vw/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T16:14:59Z",
  },
  {
    _id: "6fdcff67-17c2-4968-a482-e1664c389624",
    category: "Music",
    videoId: "3KoYJu7vx9o",
    creator: "The Hound",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSNBqWZzWZ88_Y8LtovY22UGszTX8_RbexgvVUQcw=s68-c-k-c0x00ffffff-no-rj",
    title:
      "LAGOON CHILL || KUMBALANGI NIGHTS SONG || 1 HOUR NON-STOP PLAYBACK HD AUDIO",
    description:
      "Singer : Sushin Shyam\nMusic : Suchin Shyam\nLyricts: Suchin Shyam\nIf you love gaming please visit our gaming channel \nTHE HOUND GAME ZONE :https://www.youtube.com/channel/UCRidUqwQAhon7Nu7ZQlUjrQ\r\n\nAnd thank you for watching our video",
    thumbnail: {
      url: "https://i.ytimg.com/vi/3KoYJu7vx9o/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T16:17:12Z",
  },
  {
    _id: "b20a172d-c624-412f-acd1-56b4f78e1f83",
    category: "Music",
    videoId: "FjHGZj2IjBk",
    creator: "MONOMAN",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRukfY1d1oYOASdFqTaujBHrbCealBHy5qht_7a=s88-c-k-c0x00ffffff-no-rj",
    title:
      "[Study Sleep Relax 💖] Meditation - Monoman .beautiful comment section peaceful relaxing soothing",
    description:
      "In every happy moment, I know an inevitable shadow, the Sadness, is coming. So I tend to feel both sentiments at the same time. I made this tune in one of these moments. \n\nI am also comforted in the comment section that cheers each other. Thank you.\n\n- Spotify https://bit.ly/M_Meditation\n- Apple Music https://bit.ly/Meditation_monoman\n\nconsider subscribing me 💕\n\n☆special thanks to★\nPuuung for suggesting this great idea. (Animation by Puuung)\nhttps://www.youtube.com/puuung1\n☆Grafolio original song link★\nhttp://grafolio.com/works/316537\n\n♥ Get mp3 and Sheet music (TAB included!!)\n- Become a Patron on Patreon\nhttp://patreon.com/monoman\n\nTHANK YOU\n\nCopyrightⓒ2019 MONOMAN All rights reserved\n\n---\n\nProvided to YouTube by DistroKid\n\nMeditation · Monoman\nMeditation\n℗ MONOMAN\n\nReleased on: 2019-01-22\nAuto-generated by YouTube.\n\n#study #sleep #relaxing",
    thumbnail: {
      url: "https://i.ytimg.com/vi/FjHGZj2IjBk/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T16:18:08Z",
  },

  {
    _id: "19a3fd99-e155-4df3-b2b7-12b29da8013c",
    category: "Music",
    videoId: "qAYWw67yiN0",
    creator: "Little Soul",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLR0H2JKhE8PtcaJUHCwf25YswYG7lvsyqlI_tbv=s68-c-k-c0x00ffffff-no-rj",
    title:
      "Music to put you in a better mood - Lofi playlist for study, relax, stress relief",
    description:
      'New videos are played every Monday, Wednesday and Friday 💖💖\n🎶 Listen to "Little Soul" on Spotify : https://open.spotify.com/playlist/6YuSe3suuEWlaizQKtyVkX\n🍀 Art by  Sam Yang\nhttps://www.instagram.com/samdoesarts/\nhttps://www.youtube.com/channel/UCNNOvB507MRfny7Jcv8MmOw/videos\nhttps://www.inprnt.com/gallery/samdoesarts/\n\nAll pictures are collected by me or sent by fans, I just create more.',
    thumbnail: {
      url: "https://i.ytimg.com/vi/qAYWw67yiN0/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T18:19:55Z",
  },

  {
    _id: "757d9e0c-daab-40b1-a559-937bb88e700c",
    category: "Inspirational",
    videoId: "Si5QeaehEZs",
    creator: "Mindset Mentor",
    creatorImg:
      "https://yt3.ggpht.com/M_xZT_pxAppsRpIMP5ZC5BfRrQZW_1eBZYsEK0OGr_5jVp6lSj_1a3nawY-PHqwwDXHmt0vEo7g=s68-c-k-c0x00ffffff-no-rj",
    title: "Naval Ravikant's Advice Will Leave You SPEECHLESS (MUST WATCH)",
    description:
      'Naval Ravikant shares of the best advice for Entrepreneurs and business.\n\nSpeaker : Naval Ravikant\nCredit: Joe Rogan Experience.\n\nFair Use Disclaimer\nCopyright disclaimer under section 107 of the Copyright Act 1976, allowance is made for "fair use" for purposes such as criticism, commenting, news reporting, teaching, scholarship and research. Fair use is a use permitted by copyright statute that might otherwise be infringing. Non-profit, educational or personal use tips the balance in favor of fair use.\n\n1) This video has no negative impact on the original works.\n2) This video is also for teaching purposes.\n3) It is transformative in nature.\n4) I only used bits and pieces of the videos to get point across where necessary.\n\n•All footages are licensed from Storyblocks and the video was fully edited by us.•',
    thumbnail: {
      url: "https://i.ytimg.com/vi/Si5QeaehEZs/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T18:57:36Z",
  },
  {
    _id: "596e286e-fdfb-4b93-a7c5-b25cccf7e6dd",
    category: "Inspirational",
    videoId: "TLKxdTmk-zc",
    creator: "Motivation Madness",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRau1zym_oL4UL-qSWekt550XZp4HqVLRsWWGYBmw=s68-c-k-c0x00ffffff-no-rj",
    title: "The Most Eye Opening 10 Minutes Of Your Life | David Goggins",
    description:
      "What does it take to be the TOUGHEST MAN ALIVE? Watch this video to find out! \nBuy David Goggins Best-Selling Book: https://amzn.to/36IFLAe\n\nDavid Goggins is a retired Navy SEAL, and accomplished ultra-endurance athlete. He is also the Guinness 24-hour pull-up world record holder with 4030 repetitions. There is a lot we can learn from this inspiring man.\n\nSubscribe for Motivational Videos Every Weekday, Helping You Get Through The Week! http://bit.ly/MotivationVideos\n\nFollow us on:\nInstagram: http://bit.ly/2rhGNMY\nFacebook: http://bit.ly/2r85DC3\nTwitter: http://bit.ly/2qir5TO\n\nThis video was made in collaboration with our friends from London Real.\nhttps://www.youtube.com/channel/UCCZVmatSqIMTTB8uExk8xEg\n\n----------------------------------------­­-------------------------\n\nFootage licensed through Videoblocks and Artgrid.\n\nSpeaker: DAVID GOGGINS\nInstagram: https://www.instagram.com/davidgoggins/\nFacebook: https://www.facebook.com/iamdavidgoggins\nTwitter: https://twitter.com/davidgoggins\nWebsite: https://davidgoggins.com/\n\n----------------------------------------­­-------------------------\n\nHelp us caption & translate this video!\nhttp://bit.ly/Translate4Motivation",
    thumbnail: {
      url: "https://i.ytimg.com/vi/TLKxdTmk-zc/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T18:58:26Z",
  },
  {
    _id: "e7ec1f20-3df0-4483-841e-5ab3cdbd9ba5",
    category: "Inspirational",
    videoId: "1gdHZ3wDiZc",
    creator: "WordToTheWise",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRmjk-vxCYq6hJC9wvycrfcE-xvfTyereUakzfQ=s68-c-k-c0x00ffffff-no-rj",
    title: "How To Know Yourself | Jordan Peterson | Best Life Advice",
    description:
      '"It takes a person out of the ordinary. It takes a person out of themselves."\nFor more Jordan Peterson, check out his book "12 Rules for Life": https://amzn.to/2Pg6Ws8\nTry Audible\'s free 30-day trial and enjoy 2 free audiobooks here: https://amzn.to/2MRvzxL\nYou can pre-order Dr. Peterson\'s latest book "Beyond Order: 12 More Rules For Life" here: https://amzn.to/3nVw7jD\n\n▂▂▂▂▂▂▂▂▂▂▂▂▂\n\n➤➤Speaker:\nJordan Peterson\nhttps://www.youtube.com/user/JordanPetersonVideos\nhttps://jordanbpeterson.com/\n\n➤➤Video Sources:\nApril 2019 Q and A by Jordan B Peterson\nhttps://www.youtube.com/watch?v=rgivGzjZixM\n\nPexels Video\nhttps://videos.pexels.com/\n\nVidevo\nhttps://www.videvo.net/\n\n➤➤Thumbnail ',
    thumbnail: {
      url: "https://i.ytimg.com/vi/1gdHZ3wDiZc/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T19:00:19Z",
  },
  {
    _id: "249d4b97-8ec2-4f76-a2dc-e72ab3a6903d",
    category: "Inspirational",
    videoId: "VSceuiPBpxY",
    creator: "Motiversity",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLQ3FtoYqwDf6LPVnwaqEz6qJrahXobKsuVrI-SADw=s68-c-k-c0x00ffffff-no-rj",
    title: "THE MINDSET OF A WINNER | Kobe Bryant Champions Advice",
    description:
      '"You Want First Place Come Play With Me, You Want Second Place Go Somewhere Else." KOBE BRYANT. The Mindset Of A Winner.\nMAMBA MENTALITY book: https://amzn.to/2O5n9C1\nKobe\'s new book: https://amzn.to/2LLkAlC\n\nSpecial thanks to Patrick-Bet David from Valuetainment. Subscribe to them for more inspiring interviews: http://bit.ly/ValuetainmentYouTube\n\n▶Speaker:\n\nKobe Bryant\n\nFollow Kobe:\nInstagram: https://www.instagram.com/kobebryant/\nFacebook: https://www.facebook.com/Kobe\nTwitter: https://twitter.com/kobebryant\n\n►Listen to this speech on Mindset App: http://bit.ly/TheMindsetofaWinnerMindset',
    thumbnail: {
      url: "https://i.ytimg.com/vi/VSceuiPBpxY/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T19:22:16Z",
  },
  {
    _id: "e6faaf27-ac6b-4d2d-aaec-b45a7dbe5abb",
    category: "Inspirational",
    videoId: "xcXgtki3MlA",
    creator: "Motivation Madness",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRau1zym_oL4UL-qSWekt550XZp4HqVLRsWWGYBmw=s68-c-k-c0x00ffffff-no-rj",
    title:
      "Jordan Peterson: The Video That Will Change Your Future - Powerful Motivational Speech",
    description:
      "Jordan Peterson's Life Advice Will Change Your Future. A must watch motivational speech for 2018!\n\nSubscribe for Motivational Videos Every Weekday, Helping You Get Through The Week! http://bit.ly/MotivationVideos\n\nSpecial Thanks To Jordan Peterson for allowing us to share!\nYouTube: https://www.youtube.com/user/JordanPetersonVideos\nTwitter: https://twitter.com/jordanbpeterson\n\nSupport his Patreon:\nPatreon: https://www.patreon.com/jordanbpeterson\n\nFollow us on:\nInstagram: http://bit.ly/2rhGNMY\nFacebook: http://bit.ly/2r85DC3\nTwitter: http://bit.ly/2qir5TO\n\n----------------------------------------­­-------------------------\n\nHelp us caption & translate this video!\nhttp://bit.ly/Translate4Motivation",
    thumbnail: {
      url: "https://i.ytimg.com/vi/xcXgtki3MlA/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T19:35:30Z",
  },
  {
    _id: "dcf1b4d2-a7c5-4ade-86a2-79b6533ecde4",
    category: "Inspirational",
    videoId: "azq0S0DKS50",
    creator: "MotivationHub",
    creatorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRxR0LxkA0q7Iszzh9Fggi0F7avNa45DMCnpbyf=s68-c-k-c0x00ffffff-no-rj",
    title:
      "Robert Kiyosaki 2019 - The Speech That Broke The Internet!!! KEEP THEM POOR!",
    description:
      "Robert Kiyosaki broke the internet with this life changing speech. They don't want you to see this! This is why the poor stay poor and the rich get richer!\n►RICH DAD, POOR DAD book: https://amzn.to/316zZTQ\n►Audiobook: https://amzn.to/2VIYuZ2\n\n►Stream, discover and download the most popular new motivational speeches on Mindset app: https://bit.ly/getmindsetapp\n\n►Subscribe for more inspiring videos from the greatest speakers and minds: http://bit.ly/SubscribeHub\n\n►If you struggle and have a hard time, consider taking an online therapy session with our partner BetterHelp: http://bit.ly/TryOnlineTherapyMotivationHub\n\nPlease note we receive commissions from Betterhelp when you use our referral link. Thank you for your support!\n-------------------------------------------------------------------\n\n►Special thanks to London Real! Check out their awesome channel here: https://www.youtube.com/user/LondonRealTV\n\nIf you know someone who could use this video, share it with them!\n-------------------------------------------------------------------\n\n►Speaker:\n\nRobert Kiyosaki\n\nFollow Robert Kiyosaki\nYouTube: http://bit.ly/32U5ylr\nInstagram: http://bit.ly/311vfP9\nFacebook: http://bit.ly/2KhNp8K\nTwitter: http://bit.ly/2K9OLCh\nhttps://www.richdad.com/\n\n►Follow MotivationHub:\n\nYouTube: http://bit.ly/MotivationHubYouTube\nFacebook: http://bit.ly/MotivationHubFacebook\nTwitter: http://bit.ly/MotivationHubTwitter\nInstagram: https://www.instagram.com/motivationhub/\nWebsite: http://bit.ly/MotivationHubWebsite\nMotivational Canvas Art: https://shop.motiversity.com/\nMindset App: https://link.mindsetapp.com/V21pnxiDThb\n\n►Music by Audiojungle, licensed by MotivationHub\n\n►Video footage: \nAll video footage used is either licensed through either CC-BY or from various sources. All creative commons footage is listed at the end of the video and is licensed under CC-BY 3.0. \n\n📝 Submissions\nSpeeches: http://bit.ly/MHSpeakerSubmissions \nMusic or Footage: http://bit.ly/MHMusicFootageSubmissions\n\n►Copyright disclaimer:\nWe own commercial licenses for all the content used in this video and it was fully edited by us.\n\nPlease note we receive commissions from Amazon when you use our referral links. Thank you for your support!\n\nHelp us caption & translate this video!\n\nhttps://amara.org/v/q54U/",
    thumbnail: {
      url: "https://i.ytimg.com/vi/azq0S0DKS50/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T19:39:35Z",
  },
  {
    _id: "e8d5f194-4190-43e4-a4bf-afba0f0f0923",
    category: "Inspirational",
    videoId: "Tuw8hxrFBH8",
    creator: "Motivation Ark",
    creatorImg:
      "https://yt3.ggpht.com/UCGBFsIBwAhhlj34plgVo-HwSx1jI59BTf40dIKv2vNG3RMbzY6AhU7Uz2Jimek9_Jb5eS5p-7M=s68-c-k-c0x00ffffff-no-rj",
    title: "One of the Greatest Speeches Ever | Steve Jobs",
    description:
      "Steve Jobs: The Exclusive Biography - https://amzn.to/3zKeTM6\n\n\nSteve Jobs delivers an inspirational speech. Listen to the end for the most life changing quote of all-time. Don't let anyone ever tell you that you cannot achieve your dreams.\n\nYou will be inspired and motivated to go out there and achieve your goals. I hope you all enjoy this motivational video. :)\n\nSpeaker: Steve Jobs\nSteven Paul Jobs was an American business magnate, industrial designer, investor, and media proprietor. He was the chairman, chief executive officer (CEO), and co-founder of Apple Inc.; the chairman and majority shareholder of Pixar; a member of The Walt Disney Company's board of directors following its acquisition of Pixar; and the founder, chairman, and CEO of NeXT. Jobs is widely recognized as a pioneer of the personal computer revolution of the 1970s and 1980s, along with his early business partner and fellow Apple co-founder Steve Wozniak.\n\n\n-----------------------------------------------------------------------\n\n►Follow Motivation Ark:\nSubscribe for new Motivational Videos every week: https://www.youtube.com/channel/UC9vLdyHatOhRrCwQXq3HmQQ\n\nFacebook: https://www.facebook.com/motivationark\nTwitter: https://twitter.com/ark_motivation\n\n►Music: Air - AShamaluevMusic.\nMusic Link: https://youtu.be/8XejGxLizFU\n\nThanks for watching! If you know someone who could use this video, share it with them!\n\n\nAdditional Tags:\nmotivation, motivational video, motivational speech, steve jobs, success motivational video, success motivation, daily motivation, steve jobs success story, successful, inspiration, inspirational video, biography, steve jobs success, celebrity, best success story, best motivational video, success, failure",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Tuw8hxrFBH8/mqdefault.jpg",
      width: 120,
      height: 90,
    },
    isWatchList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: Math.floor(Math.random() * 1000) + "K",
    views: Math.floor(Math.random() * 1000) + "K",
    published: "2022-04-28T19:47:51Z",
  },
];
